name: Trigger auto deployment for hilalim

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/hilalim-AutoDeployTrigger-55ac58f3-6942-4b50-9ccb-ebe0416f3cb7.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.HILALIM_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.HILALIM_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HILALIM_REGISTRY_PASSWORD }}
          containerAppName: hilalim
          resourceGroup: DefaultResourceGroup-EUS
          imageToBuild: emes/hilalim:${{ github.sha }}
          

     

